/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as Auth_onlyRouteImport } from './routes/_auth_only';
import { Route as IndexRouteImport } from './routes/index';
import { Route as Auth_onlyTemplatesRouteImport } from './routes/_auth_only/templates';
import { Route as Auth_onlySettingsRouteImport } from './routes/_auth_only/settings';
import { Route as Auth_onlyProfileRouteImport } from './routes/_auth_only/profile';
import { Route as Auth_onlyDashboardRouteImport } from './routes/_auth_only/dashboard';
import { Route as Auth_onlyAssetsRouteImport } from './routes/_auth_only/assets';
import { Route as generalTo_dashboardRouteImport } from './routes/(general)/_to_dashboard';
import { Route as generalWorkspacesSlugRouteImport } from './routes/(general)/workspaces.$slug';
import { Route as generalTo_dashboardAuthRouteImport } from './routes/(general)/_to_dashboard.auth';
import { Route as Auth_onlyWorkspacesWorkspaceIdIndexRouteImport } from './routes/_auth_only/workspaces/$workspaceId/index';
import { Route as Auth_onlyWorkspacesWorkspaceIdCanvasRouteImport } from './routes/_auth_only/workspaces/$workspaceId/canvas';
import { Route as Auth_onlyWorkspacesWorkspaceIdBuilderRouteImport } from './routes/_auth_only/workspaces/$workspaceId/builder';

const Auth_onlyRoute = Auth_onlyRouteImport.update({
  id: '/_auth_only',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const Auth_onlyTemplatesRoute = Auth_onlyTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => Auth_onlyRoute,
} as any);
const Auth_onlySettingsRoute = Auth_onlySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => Auth_onlyRoute,
} as any);
const Auth_onlyProfileRoute = Auth_onlyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => Auth_onlyRoute,
} as any);
const Auth_onlyDashboardRoute = Auth_onlyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Auth_onlyRoute,
} as any);
const Auth_onlyAssetsRoute = Auth_onlyAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => Auth_onlyRoute,
} as any);
const generalTo_dashboardRoute = generalTo_dashboardRouteImport.update({
  id: '/(general)/_to_dashboard',
  getParentRoute: () => rootRouteImport,
} as any);
const generalWorkspacesSlugRoute = generalWorkspacesSlugRouteImport.update({
  id: '/(general)/workspaces/$slug',
  path: '/workspaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any);
const generalTo_dashboardAuthRoute = generalTo_dashboardAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => generalTo_dashboardRoute,
} as any);
const Auth_onlyWorkspacesWorkspaceIdIndexRoute =
  Auth_onlyWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => Auth_onlyRoute,
  } as any);
const Auth_onlyWorkspacesWorkspaceIdCanvasRoute =
  Auth_onlyWorkspacesWorkspaceIdCanvasRouteImport.update({
    id: '/workspaces/$workspaceId/canvas',
    path: '/workspaces/$workspaceId/canvas',
    getParentRoute: () => Auth_onlyRoute,
  } as any);
const Auth_onlyWorkspacesWorkspaceIdBuilderRoute =
  Auth_onlyWorkspacesWorkspaceIdBuilderRouteImport.update({
    id: '/workspaces/$workspaceId/builder',
    path: '/workspaces/$workspaceId/builder',
    getParentRoute: () => Auth_onlyRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/assets': typeof Auth_onlyAssetsRoute;
  '/dashboard': typeof Auth_onlyDashboardRoute;
  '/profile': typeof Auth_onlyProfileRoute;
  '/settings': typeof Auth_onlySettingsRoute;
  '/templates': typeof Auth_onlyTemplatesRoute;
  '/auth': typeof generalTo_dashboardAuthRoute;
  '/workspaces/$slug': typeof generalWorkspacesSlugRoute;
  '/workspaces/$workspaceId/builder': typeof Auth_onlyWorkspacesWorkspaceIdBuilderRoute;
  '/workspaces/$workspaceId/canvas': typeof Auth_onlyWorkspacesWorkspaceIdCanvasRoute;
  '/workspaces/$workspaceId': typeof Auth_onlyWorkspacesWorkspaceIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/assets': typeof Auth_onlyAssetsRoute;
  '/dashboard': typeof Auth_onlyDashboardRoute;
  '/profile': typeof Auth_onlyProfileRoute;
  '/settings': typeof Auth_onlySettingsRoute;
  '/templates': typeof Auth_onlyTemplatesRoute;
  '/auth': typeof generalTo_dashboardAuthRoute;
  '/workspaces/$slug': typeof generalWorkspacesSlugRoute;
  '/workspaces/$workspaceId/builder': typeof Auth_onlyWorkspacesWorkspaceIdBuilderRoute;
  '/workspaces/$workspaceId/canvas': typeof Auth_onlyWorkspacesWorkspaceIdCanvasRoute;
  '/workspaces/$workspaceId': typeof Auth_onlyWorkspacesWorkspaceIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_auth_only': typeof Auth_onlyRouteWithChildren;
  '/(general)/_to_dashboard': typeof generalTo_dashboardRouteWithChildren;
  '/_auth_only/assets': typeof Auth_onlyAssetsRoute;
  '/_auth_only/dashboard': typeof Auth_onlyDashboardRoute;
  '/_auth_only/profile': typeof Auth_onlyProfileRoute;
  '/_auth_only/settings': typeof Auth_onlySettingsRoute;
  '/_auth_only/templates': typeof Auth_onlyTemplatesRoute;
  '/(general)/_to_dashboard/auth': typeof generalTo_dashboardAuthRoute;
  '/(general)/workspaces/$slug': typeof generalWorkspacesSlugRoute;
  '/_auth_only/workspaces/$workspaceId/builder': typeof Auth_onlyWorkspacesWorkspaceIdBuilderRoute;
  '/_auth_only/workspaces/$workspaceId/canvas': typeof Auth_onlyWorkspacesWorkspaceIdCanvasRoute;
  '/_auth_only/workspaces/$workspaceId/': typeof Auth_onlyWorkspacesWorkspaceIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/templates'
    | '/auth'
    | '/workspaces/$slug'
    | '/workspaces/$workspaceId/builder'
    | '/workspaces/$workspaceId/canvas'
    | '/workspaces/$workspaceId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/templates'
    | '/auth'
    | '/workspaces/$slug'
    | '/workspaces/$workspaceId/builder'
    | '/workspaces/$workspaceId/canvas'
    | '/workspaces/$workspaceId';
  id:
    | '__root__'
    | '/'
    | '/_auth_only'
    | '/(general)/_to_dashboard'
    | '/_auth_only/assets'
    | '/_auth_only/dashboard'
    | '/_auth_only/profile'
    | '/_auth_only/settings'
    | '/_auth_only/templates'
    | '/(general)/_to_dashboard/auth'
    | '/(general)/workspaces/$slug'
    | '/_auth_only/workspaces/$workspaceId/builder'
    | '/_auth_only/workspaces/$workspaceId/canvas'
    | '/_auth_only/workspaces/$workspaceId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  Auth_onlyRoute: typeof Auth_onlyRouteWithChildren;
  generalTo_dashboardRoute: typeof generalTo_dashboardRouteWithChildren;
  generalWorkspacesSlugRoute: typeof generalWorkspacesSlugRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth_only': {
      id: '/_auth_only';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof Auth_onlyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth_only/templates': {
      id: '/_auth_only/templates';
      path: '/templates';
      fullPath: '/templates';
      preLoaderRoute: typeof Auth_onlyTemplatesRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/settings': {
      id: '/_auth_only/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof Auth_onlySettingsRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/profile': {
      id: '/_auth_only/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof Auth_onlyProfileRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/dashboard': {
      id: '/_auth_only/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof Auth_onlyDashboardRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/assets': {
      id: '/_auth_only/assets';
      path: '/assets';
      fullPath: '/assets';
      preLoaderRoute: typeof Auth_onlyAssetsRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/(general)/_to_dashboard': {
      id: '/(general)/_to_dashboard';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof generalTo_dashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(general)/workspaces/$slug': {
      id: '/(general)/workspaces/$slug';
      path: '/workspaces/$slug';
      fullPath: '/workspaces/$slug';
      preLoaderRoute: typeof generalWorkspacesSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(general)/_to_dashboard/auth': {
      id: '/(general)/_to_dashboard/auth';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof generalTo_dashboardAuthRouteImport;
      parentRoute: typeof generalTo_dashboardRoute;
    };
    '/_auth_only/workspaces/$workspaceId/': {
      id: '/_auth_only/workspaces/$workspaceId/';
      path: '/workspaces/$workspaceId';
      fullPath: '/workspaces/$workspaceId';
      preLoaderRoute: typeof Auth_onlyWorkspacesWorkspaceIdIndexRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/workspaces/$workspaceId/canvas': {
      id: '/_auth_only/workspaces/$workspaceId/canvas';
      path: '/workspaces/$workspaceId/canvas';
      fullPath: '/workspaces/$workspaceId/canvas';
      preLoaderRoute: typeof Auth_onlyWorkspacesWorkspaceIdCanvasRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/workspaces/$workspaceId/builder': {
      id: '/_auth_only/workspaces/$workspaceId/builder';
      path: '/workspaces/$workspaceId/builder';
      fullPath: '/workspaces/$workspaceId/builder';
      preLoaderRoute: typeof Auth_onlyWorkspacesWorkspaceIdBuilderRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
  }
}

interface Auth_onlyRouteChildren {
  Auth_onlyAssetsRoute: typeof Auth_onlyAssetsRoute;
  Auth_onlyDashboardRoute: typeof Auth_onlyDashboardRoute;
  Auth_onlyProfileRoute: typeof Auth_onlyProfileRoute;
  Auth_onlySettingsRoute: typeof Auth_onlySettingsRoute;
  Auth_onlyTemplatesRoute: typeof Auth_onlyTemplatesRoute;
  Auth_onlyWorkspacesWorkspaceIdBuilderRoute: typeof Auth_onlyWorkspacesWorkspaceIdBuilderRoute;
  Auth_onlyWorkspacesWorkspaceIdCanvasRoute: typeof Auth_onlyWorkspacesWorkspaceIdCanvasRoute;
  Auth_onlyWorkspacesWorkspaceIdIndexRoute: typeof Auth_onlyWorkspacesWorkspaceIdIndexRoute;
}

const Auth_onlyRouteChildren: Auth_onlyRouteChildren = {
  Auth_onlyAssetsRoute: Auth_onlyAssetsRoute,
  Auth_onlyDashboardRoute: Auth_onlyDashboardRoute,
  Auth_onlyProfileRoute: Auth_onlyProfileRoute,
  Auth_onlySettingsRoute: Auth_onlySettingsRoute,
  Auth_onlyTemplatesRoute: Auth_onlyTemplatesRoute,
  Auth_onlyWorkspacesWorkspaceIdBuilderRoute:
    Auth_onlyWorkspacesWorkspaceIdBuilderRoute,
  Auth_onlyWorkspacesWorkspaceIdCanvasRoute:
    Auth_onlyWorkspacesWorkspaceIdCanvasRoute,
  Auth_onlyWorkspacesWorkspaceIdIndexRoute:
    Auth_onlyWorkspacesWorkspaceIdIndexRoute,
};

const Auth_onlyRouteWithChildren = Auth_onlyRoute._addFileChildren(
  Auth_onlyRouteChildren,
);

interface generalTo_dashboardRouteChildren {
  generalTo_dashboardAuthRoute: typeof generalTo_dashboardAuthRoute;
}

const generalTo_dashboardRouteChildren: generalTo_dashboardRouteChildren = {
  generalTo_dashboardAuthRoute: generalTo_dashboardAuthRoute,
};

const generalTo_dashboardRouteWithChildren =
  generalTo_dashboardRoute._addFileChildren(generalTo_dashboardRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Auth_onlyRoute: Auth_onlyRouteWithChildren,
  generalTo_dashboardRoute: generalTo_dashboardRouteWithChildren,
  generalWorkspacesSlugRoute: generalWorkspacesSlugRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
