/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as Auth_onlyRouteImport } from './routes/_auth_only';
import { Route as IndexRouteImport } from './routes/index';
import { Route as Auth_onlyTemplatesRouteImport } from './routes/_auth_only/templates';
import { Route as Auth_onlySettingsRouteImport } from './routes/_auth_only/settings';
import { Route as Auth_onlyProfileRouteImport } from './routes/_auth_only/profile';
import { Route as Auth_onlyDashboardRouteImport } from './routes/_auth_only/dashboard';
import { Route as Auth_onlyAssetsRouteImport } from './routes/_auth_only/assets';
import { Route as generalTo_dashboardRouteImport } from './routes/(general)/_to_dashboard';
import { Route as generalWorkspaceSlugRouteImport } from './routes/(general)/workspace.$slug';
import { Route as generalTo_dashboardAuthRouteImport } from './routes/(general)/_to_dashboard.auth';
import { Route as Auth_onlyWorkspaceWorkspaceIdCanvasRouteImport } from './routes/_auth_only/workspace.$workspaceId.canvas';
import { Route as Auth_onlyWorkspaceWorkspaceIdBuilderRouteImport } from './routes/_auth_only/workspace.$workspaceId.builder';

const Auth_onlyRoute = Auth_onlyRouteImport.update({
  id: '/_auth_only',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const Auth_onlyTemplatesRoute = Auth_onlyTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => Auth_onlyRoute,
} as any);
const Auth_onlySettingsRoute = Auth_onlySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => Auth_onlyRoute,
} as any);
const Auth_onlyProfileRoute = Auth_onlyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => Auth_onlyRoute,
} as any);
const Auth_onlyDashboardRoute = Auth_onlyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Auth_onlyRoute,
} as any);
const Auth_onlyAssetsRoute = Auth_onlyAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => Auth_onlyRoute,
} as any);
const generalTo_dashboardRoute = generalTo_dashboardRouteImport.update({
  id: '/(general)/_to_dashboard',
  getParentRoute: () => rootRouteImport,
} as any);
const generalWorkspaceSlugRoute = generalWorkspaceSlugRouteImport.update({
  id: '/(general)/workspace/$slug',
  path: '/workspace/$slug',
  getParentRoute: () => rootRouteImport,
} as any);
const generalTo_dashboardAuthRoute = generalTo_dashboardAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => generalTo_dashboardRoute,
} as any);
const Auth_onlyWorkspaceWorkspaceIdCanvasRoute =
  Auth_onlyWorkspaceWorkspaceIdCanvasRouteImport.update({
    id: '/workspace/$workspaceId/canvas',
    path: '/workspace/$workspaceId/canvas',
    getParentRoute: () => Auth_onlyRoute,
  } as any);
const Auth_onlyWorkspaceWorkspaceIdBuilderRoute =
  Auth_onlyWorkspaceWorkspaceIdBuilderRouteImport.update({
    id: '/workspace/$workspaceId/builder',
    path: '/workspace/$workspaceId/builder',
    getParentRoute: () => Auth_onlyRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/assets': typeof Auth_onlyAssetsRoute;
  '/dashboard': typeof Auth_onlyDashboardRoute;
  '/profile': typeof Auth_onlyProfileRoute;
  '/settings': typeof Auth_onlySettingsRoute;
  '/templates': typeof Auth_onlyTemplatesRoute;
  '/auth': typeof generalTo_dashboardAuthRoute;
  '/workspace/$slug': typeof generalWorkspaceSlugRoute;
  '/workspace/$workspaceId/builder': typeof Auth_onlyWorkspaceWorkspaceIdBuilderRoute;
  '/workspace/$workspaceId/canvas': typeof Auth_onlyWorkspaceWorkspaceIdCanvasRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/assets': typeof Auth_onlyAssetsRoute;
  '/dashboard': typeof Auth_onlyDashboardRoute;
  '/profile': typeof Auth_onlyProfileRoute;
  '/settings': typeof Auth_onlySettingsRoute;
  '/templates': typeof Auth_onlyTemplatesRoute;
  '/auth': typeof generalTo_dashboardAuthRoute;
  '/workspace/$slug': typeof generalWorkspaceSlugRoute;
  '/workspace/$workspaceId/builder': typeof Auth_onlyWorkspaceWorkspaceIdBuilderRoute;
  '/workspace/$workspaceId/canvas': typeof Auth_onlyWorkspaceWorkspaceIdCanvasRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_auth_only': typeof Auth_onlyRouteWithChildren;
  '/(general)/_to_dashboard': typeof generalTo_dashboardRouteWithChildren;
  '/_auth_only/assets': typeof Auth_onlyAssetsRoute;
  '/_auth_only/dashboard': typeof Auth_onlyDashboardRoute;
  '/_auth_only/profile': typeof Auth_onlyProfileRoute;
  '/_auth_only/settings': typeof Auth_onlySettingsRoute;
  '/_auth_only/templates': typeof Auth_onlyTemplatesRoute;
  '/(general)/_to_dashboard/auth': typeof generalTo_dashboardAuthRoute;
  '/(general)/workspace/$slug': typeof generalWorkspaceSlugRoute;
  '/_auth_only/workspace/$workspaceId/builder': typeof Auth_onlyWorkspaceWorkspaceIdBuilderRoute;
  '/_auth_only/workspace/$workspaceId/canvas': typeof Auth_onlyWorkspaceWorkspaceIdCanvasRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/templates'
    | '/auth'
    | '/workspace/$slug'
    | '/workspace/$workspaceId/builder'
    | '/workspace/$workspaceId/canvas';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/templates'
    | '/auth'
    | '/workspace/$slug'
    | '/workspace/$workspaceId/builder'
    | '/workspace/$workspaceId/canvas';
  id:
    | '__root__'
    | '/'
    | '/_auth_only'
    | '/(general)/_to_dashboard'
    | '/_auth_only/assets'
    | '/_auth_only/dashboard'
    | '/_auth_only/profile'
    | '/_auth_only/settings'
    | '/_auth_only/templates'
    | '/(general)/_to_dashboard/auth'
    | '/(general)/workspace/$slug'
    | '/_auth_only/workspace/$workspaceId/builder'
    | '/_auth_only/workspace/$workspaceId/canvas';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  Auth_onlyRoute: typeof Auth_onlyRouteWithChildren;
  generalTo_dashboardRoute: typeof generalTo_dashboardRouteWithChildren;
  generalWorkspaceSlugRoute: typeof generalWorkspaceSlugRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth_only': {
      id: '/_auth_only';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof Auth_onlyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_auth_only/templates': {
      id: '/_auth_only/templates';
      path: '/templates';
      fullPath: '/templates';
      preLoaderRoute: typeof Auth_onlyTemplatesRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/settings': {
      id: '/_auth_only/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof Auth_onlySettingsRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/profile': {
      id: '/_auth_only/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof Auth_onlyProfileRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/dashboard': {
      id: '/_auth_only/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof Auth_onlyDashboardRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/assets': {
      id: '/_auth_only/assets';
      path: '/assets';
      fullPath: '/assets';
      preLoaderRoute: typeof Auth_onlyAssetsRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/(general)/_to_dashboard': {
      id: '/(general)/_to_dashboard';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof generalTo_dashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(general)/workspace/$slug': {
      id: '/(general)/workspace/$slug';
      path: '/workspace/$slug';
      fullPath: '/workspace/$slug';
      preLoaderRoute: typeof generalWorkspaceSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/(general)/_to_dashboard/auth': {
      id: '/(general)/_to_dashboard/auth';
      path: '/auth';
      fullPath: '/auth';
      preLoaderRoute: typeof generalTo_dashboardAuthRouteImport;
      parentRoute: typeof generalTo_dashboardRoute;
    };
    '/_auth_only/workspace/$workspaceId/canvas': {
      id: '/_auth_only/workspace/$workspaceId/canvas';
      path: '/workspace/$workspaceId/canvas';
      fullPath: '/workspace/$workspaceId/canvas';
      preLoaderRoute: typeof Auth_onlyWorkspaceWorkspaceIdCanvasRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
    '/_auth_only/workspace/$workspaceId/builder': {
      id: '/_auth_only/workspace/$workspaceId/builder';
      path: '/workspace/$workspaceId/builder';
      fullPath: '/workspace/$workspaceId/builder';
      preLoaderRoute: typeof Auth_onlyWorkspaceWorkspaceIdBuilderRouteImport;
      parentRoute: typeof Auth_onlyRoute;
    };
  }
}

interface Auth_onlyRouteChildren {
  Auth_onlyAssetsRoute: typeof Auth_onlyAssetsRoute;
  Auth_onlyDashboardRoute: typeof Auth_onlyDashboardRoute;
  Auth_onlyProfileRoute: typeof Auth_onlyProfileRoute;
  Auth_onlySettingsRoute: typeof Auth_onlySettingsRoute;
  Auth_onlyTemplatesRoute: typeof Auth_onlyTemplatesRoute;
  Auth_onlyWorkspaceWorkspaceIdBuilderRoute: typeof Auth_onlyWorkspaceWorkspaceIdBuilderRoute;
  Auth_onlyWorkspaceWorkspaceIdCanvasRoute: typeof Auth_onlyWorkspaceWorkspaceIdCanvasRoute;
}

const Auth_onlyRouteChildren: Auth_onlyRouteChildren = {
  Auth_onlyAssetsRoute: Auth_onlyAssetsRoute,
  Auth_onlyDashboardRoute: Auth_onlyDashboardRoute,
  Auth_onlyProfileRoute: Auth_onlyProfileRoute,
  Auth_onlySettingsRoute: Auth_onlySettingsRoute,
  Auth_onlyTemplatesRoute: Auth_onlyTemplatesRoute,
  Auth_onlyWorkspaceWorkspaceIdBuilderRoute:
    Auth_onlyWorkspaceWorkspaceIdBuilderRoute,
  Auth_onlyWorkspaceWorkspaceIdCanvasRoute:
    Auth_onlyWorkspaceWorkspaceIdCanvasRoute,
};

const Auth_onlyRouteWithChildren = Auth_onlyRoute._addFileChildren(
  Auth_onlyRouteChildren,
);

interface generalTo_dashboardRouteChildren {
  generalTo_dashboardAuthRoute: typeof generalTo_dashboardAuthRoute;
}

const generalTo_dashboardRouteChildren: generalTo_dashboardRouteChildren = {
  generalTo_dashboardAuthRoute: generalTo_dashboardAuthRoute,
};

const generalTo_dashboardRouteWithChildren =
  generalTo_dashboardRoute._addFileChildren(generalTo_dashboardRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Auth_onlyRoute: Auth_onlyRouteWithChildren,
  generalTo_dashboardRoute: generalTo_dashboardRouteWithChildren,
  generalWorkspaceSlugRoute: generalWorkspaceSlugRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
